Cargo.lock, Cargo.toml, crates/mcp-apollo-server/Cargo.toml, crates/mcp-apollo-server/src/explorer.rs, crates/mcp-apollo-server/src/server.rs
Fixes:
* There were intermittent encoding problems with the URL, due to use of the wrong compression method
* If the LLM sent invalid input, it would try to use it and fail. The input is now validated. Missing fields are defaulted.
=> Fix tool to open Apollo Explorer

Cargo.lock, Cargo.toml, README.md, clippy.toml, crates/mcp-apollo-registry/Cargo.toml, crates/mcp-apollo-registry/src/files.rs, crates/mcp-apollo-registry/src/lib.rs, crates/mcp-apollo-registry/src/logging.rs, crates/mcp-apollo-registry/src/testdata/minimal_supergraph.graphql, crates/mcp-apollo-registry/src/testdata/supergraph.graphql, crates/mcp-apollo-registry/src/uplink.rs, crates/mcp-apollo-registry/src/uplink/event.rs, crates/mcp-apollo-registry/src/uplink/persisted_queries/manifest_poller.rs, crates/mcp-apollo-registry/src/uplink/schema.rs, crates/mcp-apollo-registry/src/uplink/schema/schema_query.graphql, crates/mcp-apollo-registry/src/uplink/schema/schema_stream.rs, crates/mcp-apollo-registry/src/uplink/snapshots/mcp_apollo_registry__uplink__schema__tests__schema_by_url@logs.snap, crates/mcp-apollo-registry/src/uplink/snapshots/mcp_apollo_registry__uplink__schema__tests__schema_by_url_all_fail@logs.snap, crates/mcp-apollo-registry/src/uplink/snapshots/mcp_apollo_registry__uplink__schema__tests__schema_by_url_fallback@logs.snap, crates/mcp-apollo-registry/src/uplink/uplink.graphql, crates/mcp-apollo-server/Cargo.toml, crates/mcp-apollo-server/src/custom_scalar_map.rs, crates/mcp-apollo-server/src/errors.rs, crates/mcp-apollo-server/src/explorer.rs, crates/mcp-apollo-server/src/introspection.rs, crates/mcp-apollo-server/src/main.rs, crates/mcp-apollo-server/src/operations.rs, crates/mcp-apollo-server/src/server.rs, graphql/weather/supergraph.graphql
Significant rewrite of the server to support loading the supergraph schema from Uplink. Supports hot reloading the schema. A local schema file can also be used, and also supports hot reloading as the file changes.
**Important Note** - with this change, the MCP server requires the supergraph schema SDL, similarly to Apollo Router. It will no longer work with an API or subgraph schema. To use with a local schema file, this can be composed locally (with `rover supergraph compose`) or downloaded from GraphOS (with `rover graph fetch`). The weather example has been updated with a `supergraph.graphql` file.
Changes:
* Use a state machine to run the server. This is similar to Apollo Router. The server is only ready to serve requests once the schema and operations have been loaded.
* Add code to …
=> Retrieve schema from uplink

crates/mcp-apollo-server/src/operations.rs, crates/mcp-apollo-server/src/server.rs
Logs the character size of each tool as it loads, logs the total character length of all tools and an estimate of the tokens (seems like ~4 characters is roughly a token, but will obviously vary)
Formatting I have right now, definitely open to suggestions to make it better
```
2025-04-29T19:33:04.100713Z  INFO mcp_apollo_server: Loading schema schema_path="supergraph.graphql"
2025-04-29T19:33:04.107599Z  INFO mcp_apollo_server::server: Loading operation operation_path="graphql/weather/operations/alerts.graphql"
2025-04-29T19:33:04.108761Z  INFO mcp_apollo_server::operations: Tool GetAlerts loaded with a character count of 754
2025-04-29T19:33:04.108793Z  INFO mcp_apollo_server::server: Loading operation operation_path="graphql/weather/operations/all.graphql"
2025-04-29T19:33:04.109415Z …
```
=> log character counts and estimated tokens

installers/binstall/scripts/nix/install.sh, installers/binstall/scripts/windows/install.ps1
These scripts are taken from rover and router, and modified for the MCP Server.
Tested on macOS with Apple silicon:
```console
> install.sh
downloading apollo-mcp-server from https://github.com/apollographql/apollo-mcp-server/releases/download/v0.1.0-rc.0/apollo-mcp-server-v0.1.0-rc.0-aarch64-apple-darwin.tar.gz
Moving /var/folders/yj/8v8glqls4215vyy2jddl3x_40000gp/T/tmp.B8dVOAHlzH/apollo-mcp-server to ./apollo-mcp-server ...
You can now run the Apollo MCP Server using './apollo-mcp-server'
>  ./apollo-mcp-server --help                                                                                                                                                                  (matthewhawkins@current)[ 4:33PM]
2025-05-13T22:41:08.525006Z  INFO apollo_mcp_server: Apollo MCP Server v0.1.0 …
```
=> Add install scripts

.github/workflows/release-bins.yml
* Fix an issue where a release is marked as latest in GitHub before all the artifacts are available. This causes failure for anyone trying to install while the build is running, since the installation picks up the latest release.
* Mark release candidate builds tagged with `-rc.` as pre-releases, which will also prevent them from becoming the latest release.
=> Only mark release as latest once build is complete

docs/source/best-practices.mdx
This PR fixes the links for "GraphOS-managed persisted queries" and "Introspection" to direct to the correct anchors.
=> docs: fix links in best practices documentation

.github/workflows/release-bins.yml, flake.nix, nix/apollo-mcp.nix, nix/cargo-zigbuild.patch
This PR adds support for building x86_64-apple-darwin builds to the release process. This target is currently built as a debug release until a bug is fixed in the underlying cross compiler.
See [the corresponding issue](https://github.com/rust-cross/cargo-zigbuild/issues/338) for more information relating to the bug.
=> fix(release): add x86_64-apple-darwin

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/apollo-mcp-registry/Cargo.toml, crates/apollo-mcp-registry/src/files.rs, crates/apollo-mcp-registry/src/lib.rs, crates/apollo-mcp-registry/src/uplink.rs, crates/apollo-mcp-registry/src/uplink/persisted_queries.rs, crates/apollo-mcp-registry/src/uplink/persisted_queries/event.rs, crates/apollo-mcp-registry/src/uplink/persisted_queries/manifest_poller.rs, crates/apollo-mcp-registry/src/uplink/schema.rs, crates/apollo-mcp-registry/src/uplink/schema/event.rs, crates/apollo-mcp-server/Cargo.toml, crates/apollo-mcp-server/src/event.rs, crates/apollo-mcp-server/src/introspection.rs, crates/apollo-mcp-server/src/lib.rs, crates/apollo-mcp-server/src/main.rs, crates/apollo-mcp-server/src/operations.rs, crates/apollo-mcp-server/src/server.rs, docs/source/guides/index.mdx, docs/source/quickstart.mdx, graphql/TheSpaceDevs/README.md
* The `--operations` option now support specifying a directory. All `.graphql` files in the directory will be loaded as operations.
* The `--operations` option now supports hot reloading. If a directory is specified, the MCP Server will handle files being added or removed, as well as changes to individual files. If a file is specified, it will hot reload any changes to that file.
* The event streaming has been unified - instead of having multiple spawned tasks to pick up PQ events separately from schema events, there is now one unified event stream. This required refactoring the server states to add configuration states. Only once both schema and operations events have been received does the server enter the `Starting` state.
=> Hot reload operation files and directories

flake.nix
This PR fixes an issue where the bundled `rust-toolchain.toml` file wasn't being used.
=> fix: use rust-toolchain.toml

docs/source/guides/index.mdx
The actual CLI flag is `--operations`, not `--operation`.
=> docs: update MCP Server option from --operation to --operations

crates/apollo-mcp-server/src/schema_tree_shake.rs
This fixes the schema shaker overflowing the stack if the schema is recursive. 
https://apollographql.atlassian.net/browse/GT-135
```
type Query { id: TypeA }
type TypeA { id: TypeB }
type TypeB { id: TypeA }
```
=> fix recursive schema handling

CHANGELOG.md, crates/apollo-mcp-server/src/introspection.rs, crates/apollo-mcp-server/src/schema_tree_shake.rs
fixes #70 
This PR addresses two issues with the `introspect` tool:
-  It resolves the error `argument type reason not found` that occurs when a schema contains directives.
-  It fixes the problem  where no content is returned when a schema includes the `Subscription` top-level type.
```sh
2025-05-23T19:06:04.917064Z  INFO rmcp::service: received request id=2 request=CallToolRequest(Request { method: CallToolRequestMethod, params: CallToolRequestParam { name: "introspect", arguments: Some({"depth": Number(1), "type_name": String("Query")}) } })
2025-05-23T19:06:04.934714Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-23T19:06:04.934718Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-23T19:06:04.940833Z  INFO …
```
=> Fix issues with the introspect tool

CHANGELOG.md, crates/apollo-mcp-server/src/event.rs, crates/apollo-mcp-server/src/operations.rs, crates/apollo-mcp-server/src/server.rs
- When specifying multiple operation paths, all paths were reloaded when any one changed
- Many redundant events were sent on startup, causing verbose logging about loaded operations
- Better error handling for missing, invalid, or empty operation files
=> Operation loading fixes

CHANGELOG.md, crates/apollo-mcp-server/src/operations.rs, crates/apollo-mcp-server/src/schema_tree_shake.rs
This PR fixes an error where the input schema would crash the server if it was recursive. 
for input objects, enums, and scalars it will use references where the reference has the type description, and the usages will have the field descriptions. 
review with whitespace off
=> Fix recursive inputs

crates/apollo-mcp-server/src/graphql.rs
Since GrqphQL returns JSON, use `Content::json`. This makes the output look much better in some MCP clients, such as MCP Inspector.
Also set `is_error` based on the presence of errors in the response, following the [guildlines here](https://modelcontextprotocol.io/docs/concepts/tools#error-handling-2).
=> Return JSON content and set is_error

CHANGELOG.md, crates/apollo-mcp-server/src/operations.rs
The latest version of the Rust MCP SDK supports [tool annotations](https://modelcontextprotocol.io/docs/concepts/tools#tool-annotations). Add the `readOnlyHint` for tools based on GraphQL query operations.
We can't really know without more information if mutations qualify for the `destructiveHint` or `idempotentHint`, so we don't set those for now.
=> Set the readOnlyHint for Query operations

nix/apollo-mcp.nix
This PR fixes an issue where using `nix run` failed since it would try to use the wrong binary name.
Replaces #99 
Closes #97
=> fix: allow running using nix run

docs/source/guides/index.mdx
Mixing shorthand flags (e.g. `-s`, `-o`) and full (e.g. `--schema`, `--operations`) flags in the CLI examples can confuse beginners. I have updated the user guide to ensure that we stick to full flags in the CLI examples. This change also aligns with the Odyssey course on MCP.
=> docs: use full CLI flags consistently

flake.nix
This PR fixes an issue where the container would require a mount at `/data` even if no local schemas were needed, which is typically the case when using uplink for operations.
=> fix: allow for empty mounts

.vscode/settings.json, crates/apollo-mcp-server/src/graphql.rs, crates/apollo-mcp-server/src/introspection.rs, crates/apollo-mcp-server/src/operations.rs
Extending RawOperation to include headers/variables to support operation collection data. 
Headers will act as overrides for default headers passed in by CLI
For variables I think they should act as overrides and remove them from the inputs, if they are defaults I don't think we are added any value with them. 
Ways to define variables
no changing the value, and multiple uses need to repeat the value
```
query QueryName { field1(v: "v") field2(v: "v") }
```
shared value across multiple fields, must be passed in
```
query QueryName($v: ID!) { field1(v: $v) field2(v: $v) }
```
shared value across multiple fields, can be omited and default value will be used
```
query QueryName($v: ID! = "v") { field1(v: $v) field2(v: $v) }
```
shared value across multiple fields, but cannot be passed in
``` …
```
=> Extend RawOperation to include variables and headers

docs/source/guides/index.mdx
A significant portion of our user guide is commented out (L42-L194) due to a typo.
=> docs: reveal the mistakenly commented portion of the user guide

docs/source/command-reference.mdx, docs/source/guides/index.mdx
Intel-based Macs have been supported for a while, but the doc wasn't updated.
=> Remove note about Intel-based macs

.changesets/feat_pubmodmatt_client_metadata.md, Cargo.lock, Cargo.toml, crates/apollo-mcp-registry/Cargo.toml, crates/apollo-mcp-registry/src/uplink.rs, crates/apollo-mcp-server/Cargo.toml, crates/apollo-mcp-server/src/graphql.rs, crates/apollo-mcp-server/src/main.rs
* Add `ApolloClientMetadata` for GraphQL requests. This will allow us to collect usage data for traffic from the MCP server that goes through Apollo Router
* Add a `x-apollo-mcp-server-version` header to Uplink requests. This is similar to the header router uses, `x-router-version`, and should allow collecting usage data for calls to Uplink from the MCP server
* Change the crates to pick up `workspace.package.version` and `workspace.package.author`. This ensures that `CARGO_PKG_VERSION` will be the top level Apollo MCP Server version
* Fix broken arguments that prevent the MCP server from starting up
* Fix clippy warnings
Example of router logs with the new metadata:
`2025-06-13T13:33:18.616606Z INFO router{http.route=/,http.request.method=POST,http.request.method=POST,http.request.method= …
=> Add client metadata to GraphQL requests

.changesets/fix_headers_with_colon.md, .vscode/settings.json, crates/apollo-mcp-server/src/main.rs
The server crashes when a header's value contains colons. This PR updates the header parsing logic to resolve the issue.
```sh
$ cargo run -p apollo-mcp-server -- -u --http-address 127.0.0.1 --http-port 5000 --header "X-API-KEY: service:apollo-platform:12345"
2025-06-09T16:56:48.321750Z  INFO Apollo MCP Server v0.3.0 // (c) Apollo Graph, Inc. // Licensed under MIT
Error: invalid header: x-api-key: service:apollo-platform:12345
Stack backtrace:
0: std::backtrace_rs::backtrace::libunwind::trace
at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
1: std::backtrace_rs::backtrace::trace_unsynchronized
at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
2: …
```
=> fix: handle headers with colons in value

.vscode/launch.json
Updating the `launch.json` file so that the configurations don't include the `--explorer` CLI option. The `--explorer` CLI option requires the `APOLLO_GRAPH_REF` environment variable.
=> Remove `--explorer` from launch configurations 

crates/apollo-mcp-server/src/main.rs
The args I copied from rover and router were using skip, but clap supports envs directly. Using it this way fixes the requires problem
=> fix env args with requires

.changesets/fix_jeffrey_fix_collection_update_checking.md, crates/apollo-mcp-registry/src/platform_api/operation_collections/collection_poller.rs
The update checking was off so it would update all operations on every poll. This will fix it so that it only deletes removed operations and will only update the tool list if something has changed.
=> Operation Collections - fix update checking

.changesets/breaking_jeffrey_change_default_arg_behaviour.md, crates/apollo-mcp-server/src/main.rs, docs/source/command-reference.mdx, docs/source/guides/index.mdx
- removes `--uplink`
- uplink schema will be attempted automatically if no schema is passed in
- add `--uplink-manifest` as a new way to explicitly get persisted query manifest from uplink
- default to the default mcp tools if no other operation source is passed in
=> Change default schema and operation source behaviour

docs/source/guides/index.mdx
We changed the Docker container to use Streamable HTTP instead of SSE, but the documentation does not reflect this.
https://github.com/apollographql/apollo-mcp-server/blob/2ebcdfc3baa39a36193c08df9c185f8321d9b28f/flake.nix#L185-L189
=> Docker container uses Streamable HTTP transport by default

.changesets/feat_dale_include_operation_name.md, crates/apollo-mcp-server/src/graphql.rs, crates/apollo-mcp-server/src/introspection/tools/execute.rs, crates/apollo-mcp-server/src/operations.rs
This PR updates the code to include the operation name with GraphQL requests if it's available.
```diff
{
"query":"query GetAlerts($state: String!) { alerts(state: $state) { severity description instruction } }",
"variables":{
"state":"CO"
},
"extensions":{
"ApolloClientMetadata":{
"type":"mcp",
"version":"0.4.2"
}
},
+  "operationName":"GetAlerts"
}
```
=> Include Operation Name with graphql requests

crates/apollo-mcp-server/src/graphql.rs
I had used a client metadata key from an outdated doc. The actual extension name [used by the router](https://github.com/apollographql/router/blob/413ec9c4b25ec03705237b4ceb1215d8a4b17c44/apollo-router/src/plugins/enhanced_client_awareness/mod.rs#L13) is `clientLibrary` and the key is `name` instead of `type`.
=> Fix client metadata extension name

.changesets/feat_dale_invalid_operation_types.md, crates/apollo-mcp-server/src/introspection/tools/execute.rs
This PR addresses https://github.com/apollographql/apollo-mcp-server/pull/166#discussion_r2180616810.
Tested it on Claude Desktop:
=> The execute tool should handle invalid operation types

Cargo.lock, Cargo.toml, crates/apollo-mcp-server/Cargo.toml, crates/apollo-mcp-server/src/server/states.rs, crates/apollo-mcp-server/src/server/states/starting.rs
There are new [2.x versions of the Rust MCP SDK](https://crates.io/crates/rmcp/versions). Update to the latest 2.x version.
Previously, we had pinned an old version of the SDK due to shutdown problems. But I think that was a mistake. With the latest SDK, pressing Ctrl+C will not work if there are open connections. But I believe this is likely the intended behavior. If you close all open connections, then Ctrl+C will work. The Apollo MCP Server has the same behavior here as the MCP SDK examples.
Also note that `stateful_mode` seems to affect this behavior. If `false`, it would exit the same as it did with previous SDK versions. But I'm setting `stateful_mode` to `true` here, since we'd want the advantages of stateful mode in the server.
=> Update to Rust MCP SDK version 2

.changesets/fix_pubmodmatt_rmcp_2_fix.md, crates/apollo-mcp-server/src/server/states/running.rs, crates/apollo-mcp-server/src/server/states/starting.rs
The changes to upgrade to rmcp 0.2.x caused the state machine to be blocked on startup, so no events could be processed until the axum server was shut down (for example, by Ctrl+C). Fix by spawning like the old 0.1.x method did.
=> Fix an issue with rmcp 0.2.x upgrade

.changesets/fix_pubmodmatt_rmcp_2_fix.md, CHANGELOG.md, Cargo.lock, Cargo.toml, docs/source/command-reference.mdx, scripts/nix/install.sh, scripts/windows/install.ps1
Fix an issue where the server was unresponsive to external events such as changes to operation collections.
=> release: v0.5.1

crates/apollo-mcp-registry/src/uplink.rs, crates/apollo-mcp-server/src/graphql.rs
A previous fix to the `clientLibrary` extension name only fixed one of two cases. This should allow GraphQL requests through the Apollo Router to be reported as coming from the Apollo MCP Server.
Additionally, set the correct headers on the uplink request, such that uplink requests from the Apollo MCP Server can be identified.
=> Fix clientLibrary extension name

docs/source/guides/index.mdx, docs/source/quickstart.mdx
No one would want to list every operation file manually when they can simply give the folder that contains them. 😁
=> docs: simplify operations configuration

.changesets/fix_pubmodmatt_server_info.md, CHANGELOG.md, Cargo.lock, Cargo.toml, docs/source/command-reference.mdx, scripts/nix/install.sh, scripts/windows/install.ps1
The server will now report the correct server name and version to clients, rather than the Rust MCP SDK name and version.
=> release: v0.5.2

docs/source/quickstart.mdx
This (tiny) PR:
1. Updates a couple of links located in the [Next steps section of our MCP quickstart](https://www.apollographql.com/docs/apollo-mcp-server/quickstart#next-steps) that are currently not behaving as expected:
a. "Operation schema files" currently redirects to `/guides#from-operation-schema-files`, but is meant to be `/guides#from-operation-files`
b. "When you are ready, deploy the MCP server" currently redirects to https://www.apollographql.com/docs/apollo-mcp-server/guides#deploying-the-MCP-server, but `MCP` in the URL is meant to be lowercase.
2. Renames "Operation schema files" to "Operation files" to remain consistent with what's in the `User guide`.
- Check out the updated `quickstart.mdx` file
- Go to 🔗 [Next …
=> Update links in Quickstart's `Next steps`

crates/apollo-mcp-server/src/main.rs, crates/apollo-mcp-server/src/runtime.rs
When running the MCP server without a config file, environment variables like `APOLLO_GRAPH_REF` and `APOLLO_KEY` are ignored. This results in the server failing with the message "Missing environment variable: APOLLO_GRAPH_REF," even when the variables are properly set.
The root cause appears to be the configuration loading logic, which has two separate paths:
-  **With config file**: `read_config(path)` processes both the YAML file and environment variables.
-  **Without config file**: `Config::default()` only uses defaults, ignoring environment variables.
The processing of environment variables, including the mapping of `APOLLO_GRAPH_REF` to `GRAPHOS:APOLLO_GRAPH_REF`, occurs only in the `read_config()` function.
To resolve this issue, I added the `read_config_from_env()` function, …
=> Handle environment variables when no config file is provided

crates/apollo-mcp-server/src/runtime/config.rs
I'm seeing an error like: `Error: invalid type: found string "X-Header", expected a borrowed string for key "default.headers.X-Header" in config.yaml YAML file` when running the mcp server with a config file with the headers key:
```yaml
...
headers:
X-Header: Foo
...
```
This updates the while loop to borrow the string, avoiding the error. I'm sure there is a better way to handle this, but I wanted to take a quick poke at fixing it.
=> Fix parsing headers from header file

docs/source/command-reference.mdx, docs/source/quickstart.mdx
1. Setting rover min version needed to 0.35
2. Fixing typo with `--version` in docker section which should be `--volume`.
3. Fixed an issue with the `rover dev --mcp` command example in quickstart.
=> docs: updatings docs for rover 0.35 and fixing some issues

.changesets/feat_nc_authnz.md, Cargo.lock, crates/apollo-mcp-server/Cargo.toml, crates/apollo-mcp-server/src/auth.rs, crates/apollo-mcp-server/src/auth/networked_token_validator.rs, crates/apollo-mcp-server/src/auth/protected_resource.rs, crates/apollo-mcp-server/src/auth/valid_token.rs, crates/apollo-mcp-server/src/auth/www_authenticate.rs, crates/apollo-mcp-server/src/lib.rs, crates/apollo-mcp-server/src/server.rs, crates/apollo-mcp-server/src/server/states/running.rs, crates/apollo-mcp-server/src/server/states/starting.rs
This commit adds support for OAuth authn/z flows at the MCP protocol level. This follows the [official specification](https://modelcontextprotocol.io/specification/2025-06-18/basic/authorization) and makes no other assumptions.
=> feat: add mcp auth

docs/source/best-practices.mdx, docs/source/guides/index.mdx, docs/source/quickstart.mdx
See the [deploy preview here](https://www.apollographql.com/docs/deploy-preview/727200a4f6907883f46d65cc/apollo-mcp-server/guides#introspection-tools).
Draft until a release is available that includes the `search` tool.
=> Add documentation for the search tool

docs/source/quickstart.mdx
Updating text in quickstart around the command used to make things more clear
=> docs: improve quickstart rover dev command text

docs/source/command-reference.mdx
In order to make usage of the new configuration file options easier, this commit adds an example configuration file. It also adds a few notes about proper usage of some options.
=> docs: Provide example config file for documentation

docs/source/command-reference.mdx, docs/source/guides/index.mdx
2 new sections on Auth, one in the User Guide and one in the Command Reference -> Config options.
These pages are getting quite full so we'll want to re-organize the navbar to extract them out in the future!
=> Docs: MCP auth

docs/source/command-reference.mdx, docs/source/guides/index.mdx
We added the minifySDL feature in PR #178, but we didn't include any documentation for it. This PR adds documentation for the new minify options in the `introspect` and `search` tools.
=> Add documentation for minify options in introspect and search tools

.changesets/fix_apollo_uplink_endpoints_env_var_parsing.md, crates/apollo-mcp-server/src/runtime.rs, crates/apollo-mcp-server/src/runtime/graphos.rs
The APOLLO_UPLINK_ENDPOINTS environment variables [has historically been a comma separated list of URL strings.](https://github.com/apollographql/router/blob/5b4d688a2ce52e83e1ffe861e98e8ecb87141e9f/README.md?plain=1#L48-L49) The move to yaml configuration allows us to more directly define the endpoints as a Vec. This change introduces a custom deserializer for the `apollo_uplink_endpoints` config field that can handle both the environment variable comma separated string, and the yaml-based list.
=> fix: Add custom deserializer to handle APOLLO_UPLINK_ENDPOINTS environment variable parsing

crates/apollo-mcp-server/src/auth/valid_token.rs, crates/apollo-mcp-server/src/introspection/tools/execute.rs
The test `it_rejects_different_audience` is passing because the JWT is expired, not because of an audience mismatch. This PR fixes this false positive, which could mask regressions in audience validation.
=> it_rejects_different_audience is passing due to token expiry not audience mismatch

.changesets/feat_pass_session_id.md, crates/apollo-mcp-server/src/server/states/running.rs
We're attempting to embed the apollo-mcp-server within a proxy setup for more flexible OAuth support but are running into an issue where we cannot correlate requests issued from the MCP client with outbound requests, through apollo-mcp-server, to our graphql endpoint. 
Inspecting the headers passed in from `remote-mcp`, there's an `mcp-session-id` header [that originates from the underlying `@modelcontextprotocol/sdk` library](https://github.com/modelcontextprotocol/typescript-sdk/blob/a1608a6513d18eb965266286904760f830de96fe/src/client/streamableHttp.ts#L182). Allowing this header through would not only solve our correlation issue, but provide a level of observability at the graphql service level for which clients performed what, and when. This feels generally useful and correct. So this …
=> feat: Pass `remote-mcp` mcp-session-id header along to GraphQL request

.changesets/feat_pass_session_id.md, .changesets/fix_apollo_uplink_endpoints_env_var_parsing.md, CHANGELOG.md, Cargo.lock, Cargo.toml, RELEASE_CHECKLIST.md, crates/apollo-mcp-server/src/graphql.rs, docs/source/command-reference.mdx, scripts/nix/install.sh, scripts/windows/install.ps1
This adds support for passing the `mcp-session-id` header through from `remote-mcp` via the MCP client config. This header [originates from the underlying `@modelcontextprotocol/sdk` library](https://github.com/modelcontextprotocol/typescript-sdk/blob/a1608a6513d18eb965266286904760f830de96fe/src/client/streamableHttp.ts#L182), invoked from `remote-mcp`.
With this change it is possible to correlate requests from MCP clients through to the final GraphQL server destination.
Valid tokens are failing validation with the following error when the JWT tokens contain an audience claim as an array.
```
JSON error: invalid type: sequence, expected a string at line 1 column 97
```
According to [RFC 7519 Section 4.1.3](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3), the audience claim …
=> release: v0.7.1

.changesets/fix_oidc_url.md, crates/apollo-mcp-server/src/auth/networked_token_validator.rs
Fixes #238
The MCP server currently replaces the entire path when building OIDC discovery URLs. This causes authentication failures for identity providers like Keycloak, which have path-based realms in the URL. This PR updates the URL transformation logic to preserve the existing path from the OAuth server URL.
=> Keycloak OIDC discovery URL transformation

README.md
The README was created for the `0.1` release. This adds more details about how to get started, and adds links to documentation that will be useful for anyone hoping to use Apollo MCP Server.
=> docs: Add details to the README

docs/source/index.mdx
Updating the architecture diagram in the welcome docs to replace the old SSE transport with Streamable HTTP.
=> docs: replace SSE with Streamable HTTP in the architecture diagram

.changesets/fix_openai_incompatibility.md, crates/apollo-mcp-server/src/custom_scalar_map.rs, crates/apollo-mcp-server/src/operations.rs
The MCP server is generating JSON schemas that don't match OpenAI's function calling specification. It puts `oneOf` at the array level instead of using `items` to define the JSON schemas for GraphQL list types. While some other LLMs are more flexible about this, it technically violates the [JSON Schema specification](https://json-schema.org/understanding-json-schema/reference/array) that OpenAI strictly follows.
This PR updates the list type handling logic to move `oneOf` inside `items` for GraphQL list types.
Valid input fails validation
https://jsonschema.dev/s/kqwqR
Valid input passes validation
https://jsonschema.dev/s/3jAXW
=> fix: generate openAI-compatible json schemas for list types

.github/workflows/sync-develop.yml
* ci: adding a workflow to autogen main to develop sync pr
* ci: adding a work dispatch trigger for testing
* chore: adjusting bool check for consistency
=> Gt 367 GitHub workflow to merge main into develop (#282)

.changesets/maint_hardcoded_versions.md, crates/apollo-mcp-server/src/graphql.rs
The GraphQL tests have hardcoded version strings that we need to update manually each time we release a new version. Since this isn't included in the release checklist, it's easy to miss it and only notice the test failures later.
=> test: hardcoded version strings in tests

.github/workflows/canary-release.yml, .github/workflows/ci.yml, .github/workflows/prep-release.yml, .github/workflows/release-container.yml
Updating release prep workflow and adding a canary workflow to generate a container on `develop` push.
=> ci: updating release prep and adding canary release workflow

.changesets/feat_alocay_add_basic_e2e_test.md, e2e/mcp-server-tester/local-operations/api.graphql, e2e/mcp-server-tester/local-operations/config.yaml, e2e/mcp-server-tester/local-operations/operations/ExploreCelestialBodies.graphql, e2e/mcp-server-tester/local-operations/operations/GetAstronautDetails.graphql, e2e/mcp-server-tester/local-operations/operations/GetAstronautsCurrentlyInSpace.graphql, e2e/mcp-server-tester/local-operations/operations/SearchUpcomingLaunches.graphql, e2e/mcp-server-tester/local-operations/tool-tests.yaml, e2e/mcp-server-tester/pq-manifest/api.graphql, e2e/mcp-server-tester/pq-manifest/apollo.json, e2e/mcp-server-tester/pq-manifest/config.yaml, e2e/mcp-server-tester/pq-manifest/tool-tests.yaml, e2e/mcp-server-tester/run_tests.sh, e2e/mcp-server-tester/server-config.template.json
Adding some basic e2e tests using [mcp-server-tester](https://github.com/steviec/mcp-server-tester). Currently the tool does not always exit (ctrl+c is sometimes needed) so this should be run manually.
Added a script `run_tests.sh` (may need to run `chmod +x` to run it) to run tests. Basic usage found via `./run_tests.sh -h`. The script does the following:
1. Builds test/config yaml paths and verifies the files exist.
2. Checks if release `apollo-mcp-server` binary exists. If not, it builds the binary via `cargo build --release`.
3. Reads in the template file (used by `mcp-server-tester`) and replaces all `<test-dir>` placeholders with the test directory value. Generates this test server config file and places it in a temp location.
4. Invokes the `mcp-server-tester` via `npx`.
5. On …
=> test: adding a basic manual e2e test for mcp server

.changesets/fix_fix_validate_exec_doc_validation.md, crates/apollo-mcp-server/src/introspection/tools/execute.rs, crates/apollo-mcp-server/src/introspection/tools/validate.rs, e2e/mcp-server-tester/local-operations/tool-tests.yaml, e2e/mcp-server-tester/pq-manifest/tool-tests.yaml
Contains fixes for : https://github.com/apollographql/apollo-mcp-server/issues/327
The validate tool was parsing the operation passed in to it against the schema but it wasn't performing the validate function on the ExecutableDocument returned by the Parser. This led to cases where missing required arguments were not caught by the Tool.
This change also updates the input schema to the execute tool to make it more clear to the LLM that it needs to provide a valid JSON object
=> fix: Validate ExecutableDocument in validate tool

docs/source/config-file.mdx
Adding missing documentation for overriding config options with environment variables, as flagged in https://github.com/apollographql/apollo-mcp-server/issues/288#issuecomment-3224823429
Also adds a few more helpful links to relevant pages for config options.
=> Docs: add section on overriding config options with environment variables

.changesets/maint_codecov.md, .github/workflows/verify-changeset.yml, CONTRIBUTING.md, README.md, codecov.yml, crates/apollo-mcp-registry/src/uplink/schema/event.rs
This PR adds `codecov.yml` to set up Codecov with specific coverage targets and quality standards. It helps define clear expectations for code quality. It also includes some documentation about code coverage in `CONTRIBUTING.md` and adds the Codecov badge to `README.md`.
=> Configure Codecov with coverage targets

.github/workflows/ci.yml, .github/workflows/prep-release.yml, .github/workflows/release-bins.yml, .github/workflows/release-container.yml, .github/workflows/sync-develop.yml
Not sure why Renovate isn’t opening a PR like the one it created for Rover https://github.com/apollographql/rover/pull/2694 but this change applies the same update.
=> ci: update github checkout actions

docs/source/deploy.mdx
Added instructions for configuring load balancers with Apollo MCP Server to ensure session affinity.
=> Add load balancer configuration details for Apollo MCP

.changesets/fix_lb_supergraph_new_specs.md, crates/apollo-mcp-server/src/server/states.rs
`::new` uses "default" supergraph specs, which does not include Connectors, so all connector supergraph result in an error and are parsed as standard GraphQL. This ends up exposing join directives, which is a huge waste of tokens.
=> Update SDL handling in sdl_to_api_schema function

docs/source/define-tools.mdx
Updating the docs for defining operation collections with some extra information on how variables are treated for operation collections specifically. This came up since it seems to be missing from the docs and there have been questions around how this functionality works (since it is a bit confusing at first).
=> docs: updating define operation collections section with note on variables

.changesets/feat_cors.md, .vscode/launch.json, Cargo.lock, crates/apollo-mcp-server/Cargo.toml, crates/apollo-mcp-server/src/cors.rs, crates/apollo-mcp-server/src/errors.rs, crates/apollo-mcp-server/src/lib.rs, crates/apollo-mcp-server/src/main.rs, crates/apollo-mcp-server/src/runtime.rs, crates/apollo-mcp-server/src/runtime/config.rs, crates/apollo-mcp-server/src/server.rs, crates/apollo-mcp-server/src/server/states.rs, crates/apollo-mcp-server/src/server/states/starting.rs, docs/source/_sidebar.yaml, docs/source/config-file.mdx, docs/source/cors.mdx
This PR implements comprehensive CORS support for Apollo MCP Server to enable web-based MCP clients to connect without CORS errors. The implementation and configuration draw heavily from the Router's approach. Similar to other features like health checks and telemetry, CORS is supported only for the StreamableHttp transport, making it a top-level configuration.
You can configure it like this:
```yaml
cors:
enabled: true
origins:
- https://example.com
- https://studio.apollographql.com
match_origins:
- "^http://localhost:[0-9]+$"
- "^http://127.0.0.1:[0-9]+$"
allow_credentials: true
allow_methods:
- GET
- POST
allow_headers:
- content-type
- authorization
- mcp-protocol-version
- mcp-session-id
expose_headers:
- mcp-session-id
max_age: 0
```
Minimum configuration:
```yaml
cors:
enabled: …
```
=> Add CORS support

docs/source/deploy.mdx, docs/source/quickstart.mdx, docs/source/run.mdx
Docker first checks if an image with that tag already exists locally before attempting to pull from a registry. If it finds a local image tagged as latest, it will use that one without checking if there's a newer version available remotely. This can lead to users who come back to the documentation after months to be running an old version of the server and not `latest` as they'd expect
This change add  the `--pull always` flag to ensure the container uses the most recent image from the registry rather than potentially stale local cached versions.
=> docs: Add always pull latest docker image to sample docker run commands

docs/source/define-tools.mdx
Minor edits for docs style consistency and to keep examples clearer and simpler.
Tried out persisted queries and operation collections and filling in a couple gaps
=> Docs: Clarify examples for defining tools

Cargo.lock, Cargo.toml
In PR #378, the version number somehow got reverted during the rebase. This PR only bumps the version in the main branch. I deleted the tag and release so we can ship v0.9.0 again.
=> chore(release): bumping to version 0.9.0

.changesets/fix_fix_remove_verbose_logging.md, crates/apollo-mcp-server/src/operations/operation.rs, crates/apollo-schema-index/src/lib.rs
The tracing-subscriber crate we are using to create logs does not have a configuration to exclude the span name and attributes from the log line, see implementation here, https://github.com/tokio-rs/tracing/blob/c297a37096ae1562d453624984aa5f924ab490a1/tracing-subscriber/src/fmt/format/mod.rs#L966-L982
This led to rather verbose logs on app startup looking like,
**v0.9.0**
```sh
2025-09-30T19:45:36.762634Z  INFO Apollo MCP Server v0.9.0 // (c) Apollo Graph, Inc. // Licensed under MIT
2025-09-30T19:45:36.782298Z  INFO from_document{raw_operation=RawOperation { source_text: "query GetAlerts($state: String!) {\n  alerts(state: $state) {\n    severity\n    description\n    instruction\n  }\n}\n", persisted_query_id: None, headers: None, variables: None, source_path: …
```
=> fix: remove verbose logging

docs/source/deploy.mdx
Our deployment docs include words of caution to describe how the MCP requiring sticky sessions by default necessitates fronting the service with a load balancer that can maintain sticky session by the `mcp-session-id` header in order to scale horizontally.
The rust SDK has more information and links about this functionality. Our MCP Server implementation simply exposes the configuration option. https://github.com/modelcontextprotocol/rust-sdk/issues/212
=> Describe stateful_mode: false in the deploy documentation

docs/source/deploy.mdx
`-v` should be used for volume mount instead of `-m`, which is for memory limit.
=> docs: fix wrong docker flag

docs/source/config-file.mdx
Just aligning the docs with the code:
https://github.com/apollographql/apollo-mcp-server/blob/a618e2a8dbf8708924471ac1870064dc9ba60a1a/crates/apollo-mcp-server/src/runtime/telemetry.rs#L54-L56
=> docs: correct default otel endpoint

docs/source/telemetry.mdx
The link is broken since there is no docs page for grafana integration yet.
=> docs: remove link to grafana integration
